### ISSUE TITLE
Organisation Relations with Award and Lot

### ISSUE THREAD

**Issue by hlafuente** [TBFY/ocds-ontology#5]
Good Morning,

We are using the OCDS ontology in a project with city hall in Spain. Studying how to apply the ontology we have realized that Organization only has relations with ContratingProcess but we need Organisation to be related to Award (direct and inverse relationship) and Lot (direct and inverse relationship). Because otherwise we do not know in case of having lots an Organization which of the lots has won.

Regards, and thank you very much.

**Comment by ocorcho** [comment]
The relationship isSupplierFor was already covering the relationship between Award or Contract and Organisation. This will be extended now to cover Lot, and the inverse relationship hasSupplier will be generated
