### ISSUE TITLE
The ocds:Award url does not work

### ISSUE THREAD

**Issue by hlafuente** [TBFY/ocds-ontology#8]
When I put in a browser http://data.tbfy.eu/ontology/ocds#Award redirects me to http://52.19.213.234:7200/ontology/ocds#Award and the message 'Cannot connect' appears

**Comment by fyedro** [comment]
Please, Brian/Ahmet, can you check this? I think it is redirecting to old URIs.

**Comment by elvesater** [comment]
Was fixed a long time ago. URL redirects to https://raw.githubusercontent.com/TBFY/ocds-ontology/master/model/ocds.ttl#Award
